#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjeteBibliotheque
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MiniProjetBiblio")]
	public partial class ReservationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertReservation(Reservation instance);
    partial void UpdateReservation(Reservation instance);
    partial void DeleteReservation(Reservation instance);
    #endregion
		
		public ReservationDataContext() : 
				base(global::MiniProjeteBibliotheque.Properties.Settings.Default.MiniProjetBiblioConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ReservationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReservationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReservationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ReservationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Reservation> Reservations
		{
			get
			{
				return this.GetTable<Reservation>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservation")]
	public partial class Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<System.DateTime> _datereservation;
		
		private System.Nullable<System.DateTime> _datedebutemprunt;
		
		private System.Nullable<System.DateTime> _datefinemprunt;
		
		private string _status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndatereservationChanging(System.Nullable<System.DateTime> value);
    partial void OndatereservationChanged();
    partial void OndatedebutempruntChanging(System.Nullable<System.DateTime> value);
    partial void OndatedebutempruntChanged();
    partial void OndatefinempruntChanging(System.Nullable<System.DateTime> value);
    partial void OndatefinempruntChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
		
		public Reservation()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datereservation", DbType="Date")]
		public System.Nullable<System.DateTime> datereservation
		{
			get
			{
				return this._datereservation;
			}
			set
			{
				if ((this._datereservation != value))
				{
					this.OndatereservationChanging(value);
					this.SendPropertyChanging();
					this._datereservation = value;
					this.SendPropertyChanged("datereservation");
					this.OndatereservationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datedebutemprunt", DbType="Date")]
		public System.Nullable<System.DateTime> datedebutemprunt
		{
			get
			{
				return this._datedebutemprunt;
			}
			set
			{
				if ((this._datedebutemprunt != value))
				{
					this.OndatedebutempruntChanging(value);
					this.SendPropertyChanging();
					this._datedebutemprunt = value;
					this.SendPropertyChanged("datedebutemprunt");
					this.OndatedebutempruntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datefinemprunt", DbType="Date")]
		public System.Nullable<System.DateTime> datefinemprunt
		{
			get
			{
				return this._datefinemprunt;
			}
			set
			{
				if ((this._datefinemprunt != value))
				{
					this.OndatefinempruntChanging(value);
					this.SendPropertyChanging();
					this._datefinemprunt = value;
					this.SendPropertyChanged("datefinemprunt");
					this.OndatefinempruntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
